import { StyleSheet } from "react-native";
import { colors } from "./colors";

export const apiStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  content: { padding: 20, paddingBottom: 32 },
  header: { flexDirection: "row", alignItems: "center", marginBottom: 22 },
  back: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  headerTitle: { color: colors.text, fontSize: 24, fontWeight: "800" },
  headerSubtitle: { color: colors.muted, marginTop: 3 },
  addButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: "auto",
  },
  searchRow: { flexDirection: "row", alignItems: "center", marginBottom: 18 },
  input: {
    flex: 1,
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    height: 50,
    color: colors.text,
    fontSize: 16,
  },
  searchButton: {
    height: 50,
    paddingHorizontal: 16,
    backgroundColor: colors.primary,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
  },
  searchText: { color: colors.white, fontWeight: "700" },
  center: { alignItems: "center", justifyContent: "center", paddingVertical: 60 },
  error: { color: colors.danger, textAlign: "center", lineHeight: 22 },
  pokemonCard: {
    backgroundColor: colors.surface,
    borderRadius: 22,
    alignItems: "center",
    padding: 20,
    borderWidth: 1,
    borderColor: colors.border,
  },
  pokemonImage: { width: 190, height: 190 },
  pokemonName: {
    color: colors.text,
    fontSize: 27,
    fontWeight: "800",
    textTransform: "capitalize",
    marginTop: 4,
  },
  label: { color: colors.muted, fontSize: 14, marginTop: 8 },
  chips: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 8,
    marginTop: 12,
  },
  chip: {
    backgroundColor: colors.primarySoft,
    color: colors.primary,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 7,
    overflow: "hidden",
    fontWeight: "700",
    textTransform: "capitalize",
  },
  list: { gap: 12 },
  productCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 12,
    flexDirection: "row",
    minHeight: 116,
  },
  productImage: {
    width: 92,
    height: 92,
    borderRadius: 12,
    backgroundColor: colors.background,
  },
  productBody: { flex: 1, paddingLeft: 14 },
  productTitle: {
    color: colors.text,
    fontWeight: "700",
    fontSize: 16,
    marginBottom: 6,
  },
  productDescription: { color: colors.muted, fontSize: 13, lineHeight: 18 },
  price: { color: colors.primary, fontSize: 16, fontWeight: "800", marginTop: 6 },
  infoCard: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 18,
    marginBottom: 14,
  },
  infoTitle: { color: colors.text, fontSize: 17, fontWeight: "700", marginBottom: 8 },
  infoText: { color: colors.muted, lineHeight: 22 },
  formLabel: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 7,
    marginTop: 14,
  },
  formInput: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    minHeight: 50,
    color: colors.text,
    fontSize: 16,
  },
  formTextarea: { minHeight: 110, paddingTop: 14, textAlignVertical: "top" },
  saveButton: {
    backgroundColor: colors.primary,
    minHeight: 52,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 24,
  },
  saveText: { color: colors.white, fontSize: 16, fontWeight: "700" },
});
